# v1.4 January, 2014
# https://github.com/bevry/base
language: node_js
install: "npm install; npm install docpad; cd ./node_modules/docpad; npm install; cd ../.."
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
notifications:
  email:
    recipients:
      - me@tpî.eu